services:
  bot:
    build: .
    container_name: scan_xslx_bot
    restart: unless-stopped
    env_file: .env
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS:-1847615831}
      - TEMPLATE_EXCEL=${TEMPLATE_EXCEL:-}
      - YANDEX_VISION_API_KEY=${YANDEX_VISION_API_KEY:-}
